# Form implementation generated from reading ui file 'FileTransformer.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(410, 435)
        Dialog.setMinimumSize(QtCore.QSize(410, 435))
        Dialog.setMaximumSize(QtCore.QSize(410, 435))
        font = QtGui.QFont()
        font.setPointSize(10)
        Dialog.setFont(font)
        Dialog.setSizeGripEnabled(False)
        Dialog.setModal(True)
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 9, 391, 32))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_add_files = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.pushButton_add_files.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_add_files.setObjectName("pushButton_add_files")
        self.horizontalLayout.addWidget(self.pushButton_add_files)
        self.pushButton_remove_files = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.pushButton_remove_files.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_remove_files.setObjectName("pushButton_remove_files")
        self.horizontalLayout.addWidget(self.pushButton_remove_files)
        self.pushButton_do_transform = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.pushButton_do_transform.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_do_transform.setObjectName("pushButton_do_transform")
        self.horizontalLayout.addWidget(self.pushButton_do_transform)
        self.pushButton_set_out_directory = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.pushButton_set_out_directory.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_set_out_directory.setObjectName("pushButton_set_out_directory")
        self.horizontalLayout.addWidget(self.pushButton_set_out_directory)
        self.listView_in_files = QtWidgets.QListView(parent=Dialog)
        self.listView_in_files.setGeometry(QtCore.QRect(10, 90, 390, 290))
        self.listView_in_files.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.listView_in_files.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.listView_in_files.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.MultiSelection)
        self.listView_in_files.setObjectName("listView_in_files")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(parent=Dialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 50, 161, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_2)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.comboBox_in_type = QtWidgets.QComboBox(parent=self.horizontalLayoutWidget_2)
        self.comboBox_in_type.setProperty("in_type", "")
        self.comboBox_in_type.setObjectName("comboBox_in_type")
        self.horizontalLayout_2.addWidget(self.comboBox_in_type)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(parent=Dialog)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(191, 50, 161, 31))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_3)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.comboBox_out_type = QtWidgets.QComboBox(parent=self.horizontalLayoutWidget_3)
        self.comboBox_out_type.setProperty("out_type", "")
        self.comboBox_out_type.setObjectName("comboBox_out_type")
        self.horizontalLayout_4.addWidget(self.comboBox_out_type)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(parent=Dialog)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 390, 391, 32))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_4)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.lineEdit_out_directory = QtWidgets.QLineEdit(parent=self.horizontalLayoutWidget_4)
        self.lineEdit_out_directory.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.lineEdit_out_directory.setFont(font)
        self.lineEdit_out_directory.setReadOnly(True)
        self.lineEdit_out_directory.setObjectName("lineEdit_out_directory")
        self.horizontalLayout_5.addWidget(self.lineEdit_out_directory)
        self.action_add_files = QtGui.QAction(parent=Dialog)
        self.action_add_files.setMenuRole(QtGui.QAction.MenuRole.NoRole)
        self.action_add_files.setObjectName("action_add_files")
        self.action_remove_files = QtGui.QAction(parent=Dialog)
        self.action_remove_files.setMenuRole(QtGui.QAction.MenuRole.NoRole)
        self.action_remove_files.setObjectName("action_remove_files")
        self.action_do_transform = QtGui.QAction(parent=Dialog)
        self.action_do_transform.setMenuRole(QtGui.QAction.MenuRole.NoRole)
        self.action_do_transform.setObjectName("action_do_transform")
        self.action_set_out_directory = QtGui.QAction(parent=Dialog)
        self.action_set_out_directory.setMenuRole(QtGui.QAction.MenuRole.NoRole)
        self.action_set_out_directory.setObjectName("action_set_out_directory")
        self.action_in_type_changed = QtGui.QAction(parent=Dialog)
        self.action_in_type_changed.setMenuRole(QtGui.QAction.MenuRole.NoRole)
        self.action_in_type_changed.setObjectName("action_in_type_changed")

        self.retranslateUi(Dialog)
        self.pushButton_add_files.clicked.connect(self.action_add_files.trigger)  # type: ignore
        self.pushButton_do_transform.clicked.connect(self.action_do_transform.trigger)  # type: ignore
        self.pushButton_remove_files.clicked.connect(self.action_remove_files.trigger)  # type: ignore
        self.pushButton_set_out_directory.clicked.connect(self.action_set_out_directory.trigger)  # type: ignore
        self.comboBox_in_type.currentIndexChanged['int'].connect(self.action_in_type_changed.trigger)  # type: ignore
        self.action_add_files.triggered.connect(Dialog.on_add_files)  # type: ignore
        self.action_do_transform.triggered.connect(Dialog.on_do_transform)  # type: ignore
        self.action_remove_files.triggered.connect(Dialog.on_remove_files)  # type: ignore
        self.action_set_out_directory.triggered.connect(Dialog.on_set_out_directory)  # type: ignore
        self.action_in_type_changed.triggered.connect(Dialog.on_in_type_changed)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "文件转换器"))
        self.pushButton_add_files.setText(_translate("Dialog", "添加文件"))
        self.pushButton_remove_files.setText(_translate("Dialog", "移除文件"))
        self.pushButton_do_transform.setText(_translate("Dialog", "执行转换"))
        self.pushButton_set_out_directory.setText(_translate("Dialog", "设置输出目录"))
        self.label.setText(_translate("Dialog", "输入格式："))
        self.label_3.setText(_translate("Dialog", "输出格式："))
        self.label_4.setText(_translate("Dialog", "输出目录："))
        self.action_add_files.setText(_translate("Dialog", "添加文件"))
        self.action_remove_files.setText(_translate("Dialog", "移除文件"))
        self.action_do_transform.setText(_translate("Dialog", "执行转换"))
        self.action_set_out_directory.setText(_translate("Dialog", "设置输出目录"))
        self.action_in_type_changed.setText(_translate("Dialog", "输入格式改变"))
